project_id = "vxgvmmudspqwsaedcmsl"

[functions.nurtureflow-webhook]
verify_jwt = false

[functions.nurtureflow-auth]
verify_jwt = false

[functions.nurtureflow-callback]
verify_jwt = false

[functions.nurtureflow-refresh-token]
verify_jwt = false

[functions.ghl-auth]
verify_jwt = false

[functions.ghl-callback]
verify_jwt = false

[functions.check-ghl-connection]
enabled = true
verify_jwt = true
import_map = "./functions/check-ghl-connection/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-ghl-connection/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-ghl-connection/*.html" ]
