project_id = "vxgvmmudspqwsaedcmsl"

[functions.nurtureflow-webhook]
verify_jwt = false

[functions.nurtureflow-auth]
verify_jwt = false

[functions.nurtureflow-callback]
verify_jwt = false

[functions.nurtureflow-refresh-token]
verify_jwt = false

[functions.ghl-auth]
verify_jwt = false

[functions.ghl-callback]
verify_jwt = false
